# This docker-compose will create a container containing a PostgreSQL and a Redis.
# Do not change this file unless you really know what you are doing.
# docker-compose up -d
version: '3.7'

services:

  postgres:
    image: postgres:14.0
    container_name: PostgreSQL-14.0-Chrono_Simples
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    volumes:
      - ./.docker/volumes/pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db/sql/create_databases_docker_script.sql:/docker-entrypoint-initdb.d/create_databases_docker_script.sql
    ports:
      - '5435:5432'