server:
  port: 8080
  security:
    api-key: THE_API_KEY_STRING

app:
  tax:
    deduction_amount_per_dependent: 189.59
    default_r_factor: 0.28
    pension_ceiling: 5645.8

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: jdbc:postgresql://localhost:5435/db_chrono_simples?verifyServerCertificate=false&useSSL=false
    username: $POSTGRES_USER
    password: $POSTGRES_PASSWORD
    pool:
      enabled: true
      max-size: 10
      max-idle-time: 30m

logging:
  level:
    com:
      valemobi:
        openfinance:
          pluggyconnectorapi: DEBUG

    web: ERROR

    io:
      r2dbc: ERROR
      netty: ERROR

    reactor:
      netty:
        http: ERROR
    #        http: TRACE

    org:
      springframework:
        r2dbc: ERROR
        data:
          r2dbc: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: info, metrics
  endpoint:
    health:
      show-details: never

  metrics:
    export:
      atlas:
        enabled: false